[package]
name = "surrealism-ui"
version = "0.1.4"
edition = "2021"
description = "SurrealismUI is a third-party component library built entirely using Slint"
authors = ["syf20020816@outlook.com"]
license = "MIT"
repository = "https://github.com/syf20020816/SurrealismUI"
documentation = "https://github.com/syf20020816/SurrealismUI"
keywords = ["slint-ui", "slint", "ui-components"]


[dependencies]
slint = { version = "*" }

[package.metadata.slint]
include_path = "."
